defaults: &defaults
  url: "amqp://localhost:5672"
  sample_queue_name: "psd.s2.samples"
  plate_creator_queue_name: "psd.s2.plates"
  durable: true
  empty_queue_disconnect_interval: 0
  message_timeout: 120
  sequencescape_exchange: "psd.sequencescape"
  message_persistence: true

test:
  <<: *defaults

development:
  <<: *defaults

production:
  <<: *defaults
