defaults: &defaults
  url: "amqp://localhost:5672"
  sample_queue_name: "psd.s2.samples"
  plate_management_queue_name: "psd.s2.plates"
  durable: true
  empty_queue_disconnect_interval: 0
  message_timeout: 120
  sequencescape:
    - exchange_name: "psd.sequencescape"
      exchange_type: "direct"
      routing_key: "sequencescape"
      url: "amqp://localhost:5672"
      durable: true
      message_persistence: true
      prefetch_number: 1

test:
  <<: *defaults

development:
  <<: *defaults

production:
  <<: *defaults
