plate_management: &plate_management_settings
  well_type: "Well"
  plate_type: "Plate"
  asset_type: "Asset"
  sample_type: "Sample"
  stock_dna_plate_role: "samples.rack.stock.dna"
  stock_rna_plate_role: "samples.rack.stock.rna"
  stock_dna_plate_purpose_id: 2
  stock_rna_plate_purpose_id: 183
  unassigned_plate_purpose_id: 2
  stock_plate_patterns:
    - "stock"
  item_done_status: "done"
  sanger_barcode_type: "sanger-barcode"
  plate_location: "Sample logistics freezer"
  request_sti_type: "CreateAssetRequest"
  request_type_id: 11
  request_state: "passed"
  barcode_prefixes: 
    - "ND"
    - "NR"

sample_management: &sample_management_settings
  sample_type: "Sample"
  study_sample_type: "StudySample"

defaults: &defaults
  plate_management:
    <<: *plate_management_settings
  sample_management:
    <<: *sample_management_settings

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
