plate_management:
  - '*.*.plate.create'
  - '*.*.plate.updateplate'
  - '*.*.tuberack.create'
  - '*.*.tuberack.updatetuberack'
  - '*.*.tuberack.deletetuberack'
  - '*.*.order.create'
  - '*.*.order.updateorder'
  - '*.*.platetransfer.platetransfer'
  - '*.*.transferplatestoplates.transferplatestoplates'
  - '*.*.tuberacktransfer.tuberacktransfer'
  - '*.*.tuberackmove.tuberackmove'
  - '*.*.labellable.create'
  - '*.*.bulkcreatelabellable.*'
  - '*.*.updatelabel.*'
  - '*.*.swapsamples.*'

sample_management:
  - '*.*.sample.create'
  - '*.*.sample.updatesample'
  - '*.*.sample.deletesample'
  - '*.*.bulkcreatesample.*'
  - '*.*.bulkupdatesample.*'
  - '*.*.bulkdeletesample.*'
